"""Add industry and material database flag

Revision ID: 0004_add_industry_and_material_flag
Revises: 0003_add_demand_fields
Create Date: 2026-09-18 09:12:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004_add_industry'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cpses', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('cpses', sa.Column('material_database_available', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cpses', 'material_database_available')
    op.drop_column('cpses', 'industry')
    # ### end Alembic commands ###
