"""Add CPSE DPE Hierarchy

Revision ID: 87b8190888f8
Revises: b7ea18ef2997
Create Date: 2026-09-19 16:15:47.054448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '87b8190888f8'
down_revision: Union[str, None] = 'b7ea18ef2997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sectors',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sectors_code'), 'sectors', ['code'], unique=True)
    op.create_index(op.f('ix_sectors_name'), 'sectors', ['name'], unique=True)
    op.create_table('cognate_groups',
    sa.Column('sector_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cognate_groups_code'), 'cognate_groups', ['code'], unique=True)
    op.create_index(op.f('ix_cognate_groups_name'), 'cognate_groups', ['name'], unique=True)
    op.create_index(op.f('ix_cognate_groups_sector_id'), 'cognate_groups', ['sector_id'], unique=False)
    op.add_column('cpses', sa.Column('cognate_group_id', sa.UUID(), nullable=True))
    op.add_column('cpses', sa.Column('administrative_ministry', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_cpses_cognate_group_id'), 'cpses', ['cognate_group_id'], unique=False)
    op.create_foreign_key(None, 'cpses', 'cognate_groups', ['cognate_group_id'], ['id'])
    
    # --- Data Seeding and Migration ---
    import uuid
    
    hierarchy = {
        "Agriculture": [
            "Agro Based Industries"
        ],
        "Mining & Exploration": [
            "Coal",
            "Crude Oil",
            "Other Minerals & Metals"
        ],
        "Manufacturing, Processing & Generation": [
            "Chemicals & Pharmaceuticals",
            "Defence Production",
            "Fertilizers",
            "Heavy & Medium Engineering",
            "Industrial & Consumer Goods",
            "Petroleum (Refinery & Marketing)",
            "Power Generation",
            "Steel",
            "Textiles"
        ],
        "Services": [
            "Power Transmission",
            "Trading & Marketing",
            "Transport & Logistic Services",
            "Contract & Construction and Technical Consultancy Services",
            "Hotel & Tourist Services",
            "Financial Services",
            "Telecommunication & Information Technology"
        ]
    }
    
    conn = op.get_bind()
    
    cognate_group_id_map = {}
    
    for sector_name, groups in hierarchy.items():
        sector_id = uuid.uuid4()
        sector_code = "".join([w[0].upper() for w in sector_name.replace("&", "").split() if w.isalpha()])
        conn.execute(
            sa.text("INSERT INTO sectors (id, name, code, is_active, created_at, updated_at) VALUES (:id, :name, :code, true, now(), now())"),
            {"id": sector_id, "name": sector_name, "code": sector_code}
        )
        
        for group_name in groups:
            group_id = uuid.uuid4()
            group_code = "".join([w[0].upper() for w in group_name.replace("&", "").split() if w.isalpha()])
            conn.execute(
                sa.text("INSERT INTO cognate_groups (id, sector_id, name, code, is_active, created_at, updated_at) VALUES (:id, :sector_id, :name, :code, true, now(), now())"),
                {"id": group_id, "sector_id": sector_id, "name": group_name, "code": group_code}
            )
            cognate_group_id_map[group_name] = group_id
            
    # Map existing CPSEs
    result = conn.execute(sa.text("SELECT id, sector, industry FROM cpses"))
    for row in result:
        cpse_id, sector, industry = row
        cg_id = cognate_group_id_map.get(industry)
        if cg_id:
            conn.execute(
                sa.text("UPDATE cpses SET cognate_group_id = :cg_id WHERE id = :id"),
                {"cg_id": cg_id, "id": cpse_id}
            )
        else:
            print(f"WARNING: CPSE {cpse_id} has unmapped sector/industry: {sector} / {industry}. Leaving cognate_group_id as NULL.")

    op.drop_column('cpses', 'sector')
    op.drop_column('cpses', 'industry')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cpses', sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('cpses', sa.Column('sector', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cpses', type_='foreignkey')
    op.drop_index(op.f('ix_cpses_cognate_group_id'), table_name='cpses')
    op.drop_column('cpses', 'administrative_ministry')
    op.drop_column('cpses', 'cognate_group_id')
    op.drop_index(op.f('ix_cognate_groups_sector_id'), table_name='cognate_groups')
    op.drop_index(op.f('ix_cognate_groups_name'), table_name='cognate_groups')
    op.drop_index(op.f('ix_cognate_groups_code'), table_name='cognate_groups')
    op.drop_table('cognate_groups')
    op.drop_index(op.f('ix_sectors_name'), table_name='sectors')
    op.drop_index(op.f('ix_sectors_code'), table_name='sectors')
    op.drop_table('sectors')
    # ### end Alembic commands ###
