"""Add national material intelligence fields and tables

Revision ID: 8378f8464273
Revises: 123456789abc
Create Date: 2026-09-22 00:32:13.185304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8378f8464273'
down_revision: Union[str, None] = '123456789abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_adapter_configs',
    sa.Column('adapter_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_adapter_configs_adapter_type'), 'erp_adapter_configs', ['adapter_type'], unique=False)
    op.create_table('evaluation_datasets',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('taxonomy_categories',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['taxonomy_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxonomy_categories_name'), 'taxonomy_categories', ['name'], unique=True)
    op.create_index(op.f('ix_taxonomy_categories_parent_id'), 'taxonomy_categories', ['parent_id'], unique=False)
    op.create_table('attribute_definitions',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('allowed_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['taxonomy_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attribute_definitions_category_id'), 'attribute_definitions', ['category_id'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('false_merge_rate', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_runs_dataset_id'), 'evaluation_runs', ['dataset_id'], unique=False)
    op.create_table('evaluation_labels',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('material_a_id', sa.UUID(), nullable=False),
    sa.Column('material_b_id', sa.UUID(), nullable=False),
    sa.Column('expert_label', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_a_id'], ['cpse_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_b_id'], ['cpse_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_labels_dataset_id'), 'evaluation_labels', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_evaluation_labels_material_a_id'), 'evaluation_labels', ['material_a_id'], unique=False)
    op.create_index(op.f('ix_evaluation_labels_material_b_id'), 'evaluation_labels', ['material_b_id'], unique=False)
    op.add_column('common_materials', sa.Column('manufacturer', sa.String(length=255), nullable=True))
    op.add_column('common_materials', sa.Column('manufacturer_part_number', sa.String(length=255), nullable=True))
    op.add_column('common_materials', sa.Column('attributes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('common_materials', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('common_materials', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_common_materials_manufacturer_part_number'), 'common_materials', ['manufacturer_part_number'], unique=False)
    op.create_foreign_key(None, 'common_materials', 'users', ['approved_by'], ['id'])
    op.add_column('cpse_materials', sa.Column('manufacturer_part_number', sa.String(length=255), nullable=True))
    op.add_column('cpse_materials', sa.Column('attributes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('cpse_materials', sa.Column('description_score', sa.Float(), nullable=True))
    op.add_column('cpse_materials', sa.Column('uom_score', sa.Float(), nullable=True))
    op.add_column('cpse_materials', sa.Column('classification_score', sa.Float(), nullable=True))
    op.add_column('cpse_materials', sa.Column('technical_specification_score', sa.Float(), nullable=True))
    op.add_column('cpse_materials', sa.Column('manufacturer_score', sa.Float(), nullable=True))
    op.add_column('cpse_materials', sa.Column('manufacturer_part_number_score', sa.Float(), nullable=True))
    op.add_column('cpse_materials', sa.Column('attribute_completeness_score', sa.Float(), nullable=True))
    op.add_column('cpse_materials', sa.Column('overall_readiness_score', sa.Float(), nullable=True))
    op.add_column('cpse_materials', sa.Column('readiness_band', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_cpse_materials_manufacturer_part_number'), 'cpse_materials', ['manufacturer_part_number'], unique=False)
    op.create_index(op.f('ix_cpse_materials_overall_readiness_score'), 'cpse_materials', ['overall_readiness_score'], unique=False)
    op.create_index(op.f('ix_cpse_materials_readiness_band'), 'cpse_materials', ['readiness_band'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cpse_materials_readiness_band'), table_name='cpse_materials')
    op.drop_index(op.f('ix_cpse_materials_overall_readiness_score'), table_name='cpse_materials')
    op.drop_index(op.f('ix_cpse_materials_manufacturer_part_number'), table_name='cpse_materials')
    op.drop_column('cpse_materials', 'readiness_band')
    op.drop_column('cpse_materials', 'overall_readiness_score')
    op.drop_column('cpse_materials', 'attribute_completeness_score')
    op.drop_column('cpse_materials', 'manufacturer_part_number_score')
    op.drop_column('cpse_materials', 'manufacturer_score')
    op.drop_column('cpse_materials', 'technical_specification_score')
    op.drop_column('cpse_materials', 'classification_score')
    op.drop_column('cpse_materials', 'uom_score')
    op.drop_column('cpse_materials', 'description_score')
    op.drop_column('cpse_materials', 'attributes_json')
    op.drop_column('cpse_materials', 'manufacturer_part_number')
    op.drop_constraint('common_materials_approved_by_fkey', 'common_materials', type_='foreignkey')
    op.drop_index(op.f('ix_common_materials_manufacturer_part_number'), table_name='common_materials')
    op.drop_column('common_materials', 'approved_at')
    op.drop_column('common_materials', 'approved_by')
    op.drop_column('common_materials', 'attributes_json')
    op.drop_column('common_materials', 'manufacturer_part_number')
    op.drop_column('common_materials', 'manufacturer')
    op.drop_index(op.f('ix_evaluation_labels_material_b_id'), table_name='evaluation_labels')
    op.drop_index(op.f('ix_evaluation_labels_material_a_id'), table_name='evaluation_labels')
    op.drop_index(op.f('ix_evaluation_labels_dataset_id'), table_name='evaluation_labels')
    op.drop_table('evaluation_labels')
    op.drop_index(op.f('ix_evaluation_runs_dataset_id'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index(op.f('ix_attribute_definitions_category_id'), table_name='attribute_definitions')
    op.drop_table('attribute_definitions')
    op.drop_index(op.f('ix_taxonomy_categories_parent_id'), table_name='taxonomy_categories')
    op.drop_index(op.f('ix_taxonomy_categories_name'), table_name='taxonomy_categories')
    op.drop_table('taxonomy_categories')
    op.drop_table('evaluation_datasets')
    op.drop_index(op.f('ix_erp_adapter_configs_adapter_type'), table_name='erp_adapter_configs')
    op.drop_table('erp_adapter_configs')
    # ### end Alembic commands ###
