"""Add mpn score to matches

Revision ID: db48d22d8ca0
Revises: 8378f8464273
Create Date: 2026-09-22 00:34:43.403097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'db48d22d8ca0'
down_revision: Union[str, None] = '8378f8464273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analysis', sa.Column('manufacturer_part_number_score', sa.Float(), nullable=False, server_default='0'))
    op.add_column('material_matches', sa.Column('manufacturer_part_number_score', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_matches', 'manufacturer_part_number_score')
    op.drop_column('ai_analysis', 'manufacturer_part_number_score')
    # ### end Alembic commands ###
